name:                Carnifex2
version:             0.1.0.0
github:              "githubuser/Carnifex2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Carnifex2#readme>

dependencies:
- base
- aeson
- reflex
- lens
- proto-lens
- carnifex-proto
- bytestring
- aeson-pretty
- raw-strings-qq
- casing
- proto-lens-protobuf-types

library:
  source-dirs: src
  dependencies:
    - carnifex-proto

executables:
  Carnifex2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Carnifex2

tests:
  Carnifex2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Carnifex2
