resolver: lts-10.1

packages:
- .
- carnifex-proto

extra-deps:
- git: https://github.com/TPolzer/proto-lens
  commit: dd2a6e257d63f8b73422b46aa241d6c60e3619da
  subdirs: 
    - proto-lens-protobuf-types
    - proto-lens
    - lens-labels
    - proto-lens-protoc
- bifunctors-5.4.2
- prim-uniq-0.1.0.1
