name:                carnifex-proto

extra-source-files:
- src/Carnifex/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-protoc

dependencies:
- base
- proto-lens
- proto-lens-protoc
- proto-lens-protobuf-types
- aeson
- casing
- containers
- unordered-containers
- text
- template-haskell
- time
- iso8601-time
- lens
- deepseq
- scientific
- attoparsec
- text-format
- hashable
- lens-labels

library:
  source-dirs: src
  exposed-modules:
    - Proto.Carnifex.Configuration
    - Proto.Carnifex.Configuration'Fields
    - Proto.Carnifex.Live
    - Proto.Carnifex.Live'Fields
    - Proto.Carnifex.Scoreboard
    - Proto.Carnifex.Scoreboard'Fields
    - Proto.Carnifex.EventFeed
    - Proto.Carnifex.EventFeed'Fields
    - Proto.Carnifex.JSON
    - Proto.Carnifex.JSON.TH
    - Carnifex.Reltime
